#!/bin/sh -e

# Recompile TypeScript incrementally in the background
tsc &

# When any file in out-ts/ changes, compile with rollup
find out-ts/* -type f | entr npx rollup -c rollup.config.js

# However, since find doesn't update, you'll have to restart this build script if
# you add a new file to look for changes in. I think it's possible to set up a
# loop that checks the whole directory but that's probably more resource-intensive.
