// The Akvedukto tutorial and introduction

const dialogue = {
	// When Claudia first comes in and meets Frontinus
	introduction: [
		["???", "Who has entered the Nova Anio-akvedukto?"],
		["Claudia", "Uh..."],
		["???", "Oh, it's you!"],
		["Frontinus", "Greetings, Claudia. My name is Frontinus and I am here to help."],
		["Claudia", "Is there some kind of door you're supposed to show me?"],
		["Frontinus", "I see. Of course that's why you're here..."],
		["Frontinus", "Anyway, before we get to that, there are things you need to learn."],
		["Frontinus", "Are you really aware of the danger around these parts?"],
		["Claudia", "Are you aware of the lack of danger?"],
		["Frontinus", "No, but that's because the lack of danger does not exist."],
		["Claudia", "Then, what danger could you be referring to?"],
		["Frontinus", "I mean, of course, the mortal danger!"],
		["Claudia", "..."],

		["Frontinus", "Now that you're aware, it's time to prepare!"],
		["Frontinus", "How? Through an interactive tutorial!"],
		["Claudia", "How is this necessary?"],
		["Claudia", "If there does turn out to be danger, I'll figure out how to avoid it on my own."],
		["Frontinus", "You can, but not everybody can."],
		["Frontinus", "Do you understand?"],
		["Claudia", "Uh... Maybe?"],
		["Frontinus", "Now, then, let's begin."],
		["Frontinus", "Oh, and don't worry. I'll re-explain anything you mess up."],
		["Claudia", "That won't be necessary either..."]
	],

	// Frontinus explains how Claudia can use X to attack him
	attacking: [
		["Frontinus", "First things first: attacking."],
		["Frontinus", "Do you see the '05' in the top right of the screen?"],
		["Frontinus", "Those are the pretend life points that I've created."],
		["Frontinus", "To kill an enemy, you must reduce their life points to zero, of course."],
		["Claudia", "If I do that, wouldn't it make *me* the mortal danger?"],
		["Frontinus", "No, because it's self-defense."],
		["Claudia", "How can I determine whether an attack will be self-defense or not?"],
		["Frontinus", "Don't worry about that."],
		["Frontinus", "For now, understand that you attack using the X key."],
		["Frontinus", "You will see a blue ring around you, which represents your attack range."],
		["Frontinus", "Once I'm in your attack range, using X will successfully deal damage."],
		["Claudia", "Are you really telling me to kill you?"],
		["Frontinus", "Don't misunderstand: I am actually invincible."],
		["Frontinus", "These life points are only for the convenience of the tutorial."],
		["Frontinus", "Anyway, you can't spam X five times to 'kill' me instantly."],
		["Claudia", "Who's going to stop me?"],
		["Frontinus", "You will stop yourself."],
		["Frontinus", "After an attack, or any other action, for that matter, you'll have a cooldown."],
		["Frontinus", "This will be represented with a wide, blue bar on the right edge of the screen."],
		["Frontinus", "Only once the cooldown is finished can you start a new action."],
		["Frontinus", "Confused yet?"],
		["Claudia", "Who do you take me for? I'm not so easily confused."],
		["Claudia", "Not on your terms, anyhow."],
		["Frontinus", "Well, experiment with attacking on your own now."],
		["Frontinus", "I will explain the next aspect of combat once you deplete my life points."],
	],

	// Frontinus explains the timing of his attacks (number pattern)
	timing: [
		["Claudia", "Whoa, hold on. I was next to you just a second ago. How am I back here?"],
		["Frontinus", "What kind of question is that?"],
		["Frontinus", "And what kind of answer are you looking for?"],
		["Claudia", "Well..."],
		["Frontinus", "Those were rhetorical, by the way."],
		["Frontinus", "Anyway, it looks like you've gotten the hang of attacking."],
		["Frontinus", "It's clear now that you are an innately violent individual."],
		["Frontinus", "You really have no problem abusing a civil engineer like that?"],
		["Claudia", "You're the one who urged me to do so..."],

		["Frontinus", "The next concept is timing."],
		["Frontinus", "You have noticed the '05' printed on my face, haven't you?"],
		["Claudia", "I initially assumed that that was a second display of life points."],
		["Claudia", "The number never changed while I attacked you, however."],
		["Frontinus", "That's because this number is not directly connected to life points at all."],
		["Frontinus", "Instead, it's my attack counter!"],
		["Frontinus", "During combat, I will decrement this number."],
		["Frontinus", "Then, once it hits zero, I will swing my sword and attack you back."],
		["Claudia", "Ah, so *you* are the mortal danger."],
		["Claudia", "Wouldn't chaining yourself up be the more surefire way of removing risk?"],
		["Frontinus", "Again, don't jump to unfortunate conclusions."],
		["Frontinus", "My weapon is incapable of creating real hurt."],
		["Frontinus", "Instead, its purpose is practice; I can simulate damage."],
		["Claudia", "Well then, do I have life points too? Would they decrease if I was to get hit?"],
		["Frontinus", "Are you referencing the '99' in the top left? We'll get to that later."],
		["Frontinus", "For now, try to completely avoid being hit."],
		["Frontinus", "Remember: I strike when my attack counter hits zero."],

		["Claudia", "And the only way it changes is by a decrease of one, it sounds like?"],
		["Claudia", "Why would you make it so predictable?"],
		["Frontinus", "Hey, I don't control it myself."],
		["Frontinus", "The pattern of a foe's attack counter is determined by the foe's conviction."],
		["Claudia", "Foe? Wouldn't I be a 'foe' from my opponent's perspective?"],
		["Claudia", "Why don't I have an attack counter to go along with that?"],
		["Frontinus", "Well, you're special. The world revolves around you, Claudia."],
		["Claudia", "What kind of answer is that?"],

		["Frontinus", "Disregard that subject too."],
		["Frontinus", "Now, try depleting my health like last time."],
		["Frontinus", "This time, however, you will need to anticipate my attacks."],
		["Frontinus", "If you mess up, I'll rewind time back to the start of this conversation."],
		["Frontinus", "Then, you can remind yourself of the instructions."],
		["Frontinus", "This is what I was referring to when you first arrived."],
		["Claudia", "Rewind time? I thought only Tiberius was capable of time travel."],
		["Frontinus", "Tiberius Claudius Caesar Britannicus? I haven't heard that name in a while."],
		["Frontinus", "Well then, have a go."],
	],

	// Frontinus explains being hit and healing
	healing: [
		["Frontinus", "Great, your brain is capable of grasping the concept of counting."],
		["Claudia", "You say that as if your ability to 'grasp concepts' is superior to mine."],
		["Frontinus", "Is it not?"],
		["Claudia", "It's not."],
		["Claudia", "Next time you consider making such a nefarious implication, think again."],
		["Frontinus", "The next concept you need to grasp is healing."],
		["Frontinus", "Successful as your timing is, it won't ever be perfect."],
		["Frontinus", "You're not me, after all."],
		["Claudia", "..."],
		["Frontinus", "Thus, it's important to be able to survive being hit."],
		["Claudia", "Are you going to explain whether or not I have life points now?"],
		["Frontinus", "You do have life points, Claudia."],
		["Frontinus", "However, they work slightly differently from that of your enemies."],
		["Frontinus", "When I hit you, your life points will decrease, but that's not all."],
		["Frontinus", "Additionally, your life will become 'threatened'."],
		["Claudia", "Isn't it threatened the second combat starts?"],
		["Frontinus", "'Threatened' is a specific, identifiable state."],
		["Frontinus", "You'll know you're threatened because your life points display will turn red."],
		["Claudia", "Why should I care if it's red or not?"],
		["Frontinus", "I was about to get to that."],
		["Frontinus", "The thing is, your life points are effectively reduced to one while threatened."],
		["Frontinus", "So, if you are hit while threatened, you will die, regardless of how many remain."],
		["Claudia", "How is that different from having two life points total?"],
		["Frontinus", "This is where healing comes into play."],
		["Frontinus", "You're incapable of raising your life points, but you can do something else."],
		["Claudia", "Unthreaten myself?"],
		["Frontinus", "That's right. Pressing C will heal you, removing the 'threatened' state."],

		["Claudia", "Hmm..."],
		["Claudia", "Wait, so does that mean it's optimal to spam C during your attack?"],
		["Claudia", "That's unfun, annoying, nonsensical, etc."],
		["Frontinus", "No, that's not a particularly good idea, because you haven't heard the catch."],
		["Claudia", "What are you talking about?"],
		["Frontinus", "The catch is that healing is not instant."],
		["Frontinus", "After pressing C to heal, you will start a healing (and action) cooldown."],
		["Frontinus", "The healing cooldowns shows up yellow in the second quarter of the screen."],
		["Frontinus", "Only once it's finished does the heal activate."],
		["Claudia", "How fast is the healing cooldown compared to the action cooldown?"],
		["Frontinus", "Figure it out yourself."],
		["Frontinus", "Also, your movement speed will be halfed while the cooldown is running."],
		["Claudia", "What if I *want* to move slowly?"],
		["Frontinus", "In that case, you should hold Shift while moving, but it has nothing to do with healing."],

		["Frontinus", "Alright, it's time for you to try healing on your own."],
		["Frontinus", "I will cut off your means of escape using some walls, forcing you to take damage."],
		["Frontinus", "To survive long enough to defeat me, you'll have to heal after every attack."],
		["Frontinus", "Understand?"],
		["Claudia", "I understand, yes..."],
		["Claudia", "...but you wouldn't understand if our roles were switched."],
		["Claudia", "Your concept comprehension capacity is largely non-existent, after all."],
		["Frontinus", "..."],
		["Frontinus", "Another note is that this strategy of sponging damage through healing is generally wrong."],
		["Frontinus", "In this case, it works, since I've generously provided you with 99 life points."],
		["Frontinus", "Usually, however, you'll have far less. You'll quickly die if you waste them."],
		["Claudia", "That's not true. I could waste all except one and then kill my enemy with one left."],
		["Frontinus", "Whatever you say. Let's begin."],
	],

	// Frontinus explains dodging with Z to avoid damage
	dodging: [
		["Claudia", "That was far too easy."],
		["Frontinus", "Oh? It looked as if you were struggling to progress..."],
		["Claudia", "Seems like you're incapable of making valid inferences, as usual."],
		["Claudia", "Anyway, am I done?"],
		["Frontinus", "Not quite. There is one last element: dodging."],
		["Claudia", "Didn't I already dodge your attacks during the attack counter practice?"],
		["Frontinus", "You dodged them, but you didn't *dodge* them."],
		["Frontinus", "'Dodging' is a specific action triggered by the Z key."],
		["Frontinus", "When pressing Z, a dodge cooldown will start."],
		["Frontinus", "This one is green and positioned in the third quarter of the screen."],
		["Frontinus", "While the dodge cooldown is running, you will be immune to all damage."],
		["Frontinus", "Pretty simple, right?"],

		["Claudia", "What stops me from staying invincible indefinitely by spamming Z?"],
		["Frontinus", "Where's the fun in that? You will once again stop yourself."],
		["Frontinus", "Since dodging is an action, it will have an accompanied action cooldown."],
		["Frontinus", "However, the action cooldown lasts longer than the dodge cooldown."],
		["Frontinus", "Are you confused, or do you see what I'm saying?"],
		["Claudia", "I get it..."],
		["Claudia", "The dodge cooldown is shorter, so when it ends, the action cooldown will be running."],
		["Claudia", "And since the action cooldown is running, I'll be unable to start a new dodge."],
		["Claudia", "During the interval between the dodge cooldown ending and my next dodge starting..."],
		["Claudia", "...I will be completely open to damage."],
		["Frontinus", "Is that right? I kind of... got lost..."],
		["Claudia", "Ha! Your ability to maintain stable attention subceeds mine."],
		["Claudia", "Do you understand how tiny you really are?"],
		["Claudia", "I don't care if you call yourself invincible. I am one hundred times more powerful."],
		["Frontinus", "Really? Or are you just incapable of effectively communicating ideas?"],
		["Claudia", "N-no! We both know that you're just deflecting."],
		["Frontinus", "Well then, demonstrate your supposed ability."],
		["Frontinus", "Kill me without taking damage."],
		["Claudia", "No problem for me."],

		["Claudia", "Oh, but I have one question regarding the previous trial."],
		["Claudia", "What was that red cooldown in the first quarter of the screen?"],
		["Frontinus", "You talk big yet fail to grasp such an obvious idea..."],
		["Frontinus", "How can you be so blatantly unaware of your own faults?"],
		["Claudia", "..."],
		["Frontinus", "No response, huh?"],
		["Frontinus", "Well, the red cooldown is the damage cooldown, of course."],
		["Frontinus", "My sword passed through you for many frames."],
		["Frontinus", "Why then, did you only take damage once per swing?"],
		["Claudia", "Oh, it's becau-"],
		["Frontinus", "-because damage is turned off for the rest of the swing?"],
		["Frontinus", "As part of the code for the sword, which would remember whether you were hit or not?"],
		["Claudia", "That's actually not what I was goi-"],
		["Frontinus", "Wrong answer! In reality, it's because of the damage cooldown!"],
		["Claudia", "..."],
		["Frontinus", "As soon as you take damage, the damage cooldown starts."],
		["Frontinus", "Then, for the duration of the cooldown, you're immune!"],
		["Frontinus", "This gives you a moment to get back on your feet."],
		["Claudia", "I was about to sa-"],
		["Frontinus", "Welp, enough questions! Practice using Z to dodge!"],
	],

	// Frontinus explains replaying the tutorial and going to Lerwick
	conclusion: [
		[null, "At the 1980 Olympics, Brezhnev begins his speech."],
		["Brezhnev", "O!"],
		[null, "(Applause)"],
		["Brezhnev", "O!"],
		[null, "(An ovation)"],
		["Brezhnev", "O!!!"],
		[null, "(The whole audience stands up and applauds.)"],
		[null, "An aide comes running to the podium and whispers..."],
		["Aide", "Leonid Ilyich, those are the Olympic logo rings. You don't need to read all of them!"]
	]
}

export default dialogue
