// Interactions in Perinthus
const dialogue = {
	Ovicula: [
		["Claudia", "Hey, want to know what my position on the theory of mind is?"],
		["Ovicula", "I don't care. Go away!"]
	],

	Dorus: [
		["Claudia", "Hey Dorus, how's it going?"],
		["Dorus", "Greetings, Claudia. I figured something pretty important out recently."],
		["Claudia", "Important in what context and for whom?"],
		["Dorus", "You find that question more interesting than what it is I actually figured out...?"],
		["Dorus", "I'll keep that brief and say that it's 'important' for *me*, in every sense."],
		["Claudia", "Okay, well, what is it?"],
		["Dorus", "First, name a superhuman ability. Please stay intellectually honest this time."],
		["Claudia", "Sure, sure. Uh, how about the ability to make arbitrary physical objects levitate?"],
		["Dorus", "Great example! What I've figured out how to do... is just that."],
		["Claudia", "Huh? What if I had named a totally different ability instead?"],
		["Claudia", "Surely my words in this moment aren't determining prior events, are they?"],
		["Dorus", "You're overthinking it. I've figured out *every* ability."],
		["Dorus", "Therefore, anything you would have stated would apply."],
		["Claudia", "I've been going along for amusement, but this is starting to sound ridiculous."],
		["Dorus", "Of course it is."],
		["Dorus", "However, it all starts with one important concept: one that we can probably agree on."],
		["Claudia", "Which is...?"],
		["Dorus", "It's the idea that in practice, our impressions of events are more real than the events themselves."],

		["Claudia", "Is this something religious? I thought you were against that."],
		["Claudia", "Just last week you were explaining your anti-Pascal's wager..."],
		["Dorus", "Don't take this the wrong way. Let me give you an example to clear it up."],
		["Dorus", "Think about the concept of 'getting rich'."],
		["Dorus", "It's something almost anybody 'wishes', isn't it?"],
		["Claudia", "Sure...?"],
		["Dorus", "Well, why do they actually want to get rich?"],
		["Dorus", "It's because they believe that being rich will make them happier and more satisfied."],
		["Dorus", "Right?"],
		["Claudia", "I can agree that the state of wealth isn't inherently desirable, if that's what you mean."],
		["Dorus", "Exactly! It's only a means to the actual end of happiness."],
		["Dorus", "In that sense, being happy without being rich is just as real as actually being rich."],
		["Claudia", "From the person's perspective, yeah."],
		["Dorus", "Now, apply that same logic to the concept of superpowers."],
		["Dorus", "If I really could make objects levitate, why would I ever use it?"],
		["Claudia", "You'd do it to gain some kind of satisfaction, as the person who strives to be rich does."],
		["Dorus", "Bingo! Whether it's to impress a person, make an honorable act, simply amuse myself..."],
		["Dorus", "The levitation's only ultimate purpose, from my perspective, is to bring me happiness."],

		["Claudia", "And therefore, if you're 'happy', it means you can levitate? Hold on... I object."],
		["Claudia", "Let's go back to the wealth example."],
		["Claudia", "Wanting to be rich doesn't mean that your 'happy' state is identical to your 'rich' state."],
		["Claudia", "I might be a generally happy person, but I could still want to pursue wealth."],
		["Claudia", "In that case, the wealth isn't necessary for happiness, but it's still a goal."],
		["Claudia", "One that is *not* met."],
		["Claudia", "Do you see what I'm saying?"],

		["Dorus", "Oh ho! I was actually trying to simplify the idea for you."],
		["Dorus", "You've exceeded my expectations, however. So, let us drop the useless, regressive abstraction."],
		["Dorus", "Here's the jump:"],
		["Dorus", "The state's existence is equal to your desire for it, not to your happiness overall."],
		["Claudia", "So..."],
		["Dorus", "If I want to be rich, I'm not rich. If I don't care, then I might as well already be rich."],
		["Claudia", "Then, applied back..."],
		["Claudia", "If you're 100% content with your lack of superpowers, it's the same as actually having them...?"],
		["Dorus", "Exactly! It goes for any context!"],

		["Claudia", "Okay, well there's still the matter of the elephant in the room."],
		["Claudia", "Is it really true that you're perfectly satisfied with not having superpowers?"],
		["Claudia", "That would mean that you don't care about your own life, wouldn't it?"],
		["Dorus", "No, I *do* want superpowers."],
		["Claudia", "So then it all breaks down! You want to levitate but can't, so you can't!"],

		["Dorus", "Hold on! What I said was that I figured out *how*..."],
		["Dorus", "Each aspect of want is psychological, is it not?"],
		["Dorus", "And I've figured out *how* to control my psychology."],
		["Dorus", "So, I know how to stop caring about levitating, which means that I've figured out how to levitate."],
		["Claudia", "And you can apply the same method anywhere?"],
		["Dorus", "Yes. Take the aversion to death, for example."],
		["Dorus", "Currently, I fear death, but I'm capable of modifying my psychology in a way that changes that."],
		["Dorus", "At that point, I'm content no matter if I live or die."],

		["Claudia", "Okay then, get to the point."],
		["Claudia", "How is it that you can perfectly control your own psychology?"],
		["Dorus", "I can't do it perfectly, and I haven't experimented much yet."],
		["Dorus", "It's mostly theoretical."],
		["Claudia", "Well, what's the theory, then?"],
		["Dorus", "That... I won't tell you."],
		["Claudia", "...."],
		["Claudia", "Were you just messing with me this whole time?"],
		["Dorus", "No, I haven't had any intention to deceive."],
		["Dorus", "I thought you'd be interested in the general idea behind it, which I've already explained."],
		["Claudia", "But it's all useless if I can't implement it!"],
		["Dorus", "Here, I'll give you a hint."],
		["Dorus", "The strategy I've discovered, you already know its name."],
		["Dorus", "You just don't know that it's its name."],
		["Dorus", "And of this name, the first two letters are 'Me'."],
		["Claudia", "Does 'first' imply that it consists of more than two letters?"],
		["Claudia", "If it's just 'Me', that would be stupid, right?"],
		["Dorus", "Yes, there are more than two letters."],
		["Dorus", "Well, go figure it out."],
		[null, "Claudia sighs deeply."],
		["Claudia", "Goodbye, Dorus."],
		["Dorus", "Farewell, Claudia. Remember: I wasn't joking."],
 	],

	Palinurus: [
	 	["Claudia", "Hey Palinurus. What are you doing?"],
	 	["Claudia", "Wait, are you watching... TikTok?"],
	 	["Claudia", "Hah, what an awful waste of time."],
	 	["Palinurus", "Shut up. You have no right to judge me."],
	 	["Claudia", "Think about your life for a second."],
	 	["Claudia", "Do you really need to keep using your phone like that?"],
	 	["Palinurus", "Shut up! I enjoy it, so I'm going to do it!"],
	 	[null, "Claudia shakes her head."],
	 	["Claudia", "You don't. That's the thing."],
		["Claudia", "Just delete it already. You will feel better."],
	 	["палинурус", "перестань уже беспокоить меня!"],
	 	["Claudia", "Switching languages doesn't change reality."],
	 	["Claudia", "Whatever. I have better things to do."]
 	]
}

export default dialogue
