// Interactions in Lerwick
const dialogue = {
	Calypso: [
		["Calypso", "Ugh..."],
		["Calypso", "I'm so lost."],
		["Claudia", "Physically? I believe you're in Lerwick."],
		["Calypso", "No, not like that."],
		["Calypso", "I'm overwhelmed with goals and things to do..."],
		["Calypso", "How can I ever hope to achieve it all?"],
		["Claudia", "I'm not your th-"],
		["Claudia", "Actually... sure, tell me about it."],
		["Claudia", "What, specifically, are you having trouble with?"],
		["Calypso", "Well, there are a number of general activities that I want to accomplish."],
		["Calypso", "I want to play shogi, practice violin, write more of my book, exercise, learn some programming..."],
		["Calypso", "But I can never seem to make room in my 24 hours."],
		["Calypso", "How do I go about changing that?"],
		["Calypso", "Please don't tell me to dream lower..."],

		["Claudia", "Let me think for a second."],
		[null, "..."],
		["Claudia", "First of all, what gave you the idea that you *have* to fit it into one day?"],
		["Calypso", "Huh? Are you not familiar with the concept of microhabits?"],
		["Calypso", "The idea is to shorten each activity down into a small chunk, which can be performed every day."],
		["Calypso", "It's not a particularly well-defined term, though. This is my interpretation."],
		["Claudia", "Well? Are they working? Surely not, if you're in this predicament."],
		[null, "Calypso sighs."],
		["Calypso", "No, they're not. Half the time, my plans fall apart..."],
		["Calypso", "The other times, I'm never able to accomplish anything meaningful in any of them."],
		["Calypso", "Even in the long-term, I'm not making anywhere /close/ to sufficient progress!"],
		["Calypso", "I don't want to die with my plans unfinished! Why can't I go faster!?"],

		["Claudia", "From what it sounds like, microhabits are inherently unproductive."],
		["Calypso", "Wh-what?"],
		["Claudia", "Are you familiar with the concept of batching?"],
		["Claudia", "The event of context switching is quite taxing on the human mind."],
		["Claudia", "So, the most efficient way to complete tasks is through uninterrupted focus."],
		["Claudia", "Of course, this gets more complicated when you introduce attention span, and so on."],
		["Claudia", "But that's the general idea."],
		["Calypso", "Batching, huh? Yeah, I've heard of that. I use that kind of strategy for doing chores."],
		["Claudia", "Well, then why not apply it to everything?"],
		["Calypso", "Everything? What..."],
		["Claudia", "Take your goal of learning programming, for example."],
		["Claudia", "Why not choose a 'programming' day, where you spend all free time in that day on programming?"],
		["Claudia", "You'll accomplish far more than if you had spent the same amount of time distributed in tiny periods."],
		["Calypso", "That's true! Why did I only think of batching in the context of things I 'had' to do?"],
		["Claudia", "However, you need to be careful in adapting the strategy to the habit."],
		["Claudia", "Take exercise, for instance."],
		["Claudia", "One day of batched exercise would be less effective, rather than more effective, wouldn't it?"],

		["Calypso", "That's also true... what now, then?"],
		["Claudia", "Well, divide your habits based on their optimal time allocation."],
		["Claudia", "I'm not particularly familiar with any of the fields you're interested in."],
		["Claudia", "But, I would guess that writing, programming, and shogi are best done in concentrated time slots."],
		["Claudia", "On the other hand, violin and exercise need to be distributed."],
		["Claudia", "I could be wrong, though. You're the expert, so you have to make the decisions."],
		["Calypso", "Then, how do I decide which to spend time on?"],
		["Claudia", "Why not continue with the daily habits as daily habits, while pushing the rest to batched days?"],
		["Claudia", "Today, after finishing your exercise and violin practice, program away the rest of the day."],
		["Claudia", "Tomorrow, pick something else."],
		["Calypso", "But how do I decide what to do on which day?"],
		["Claudia", "Hey, you need to be able to largely figure out your systems on your own."],
		["Claudia", "I'd use a digital calendar and a frequency-importance schedule."],
		["Claudia", "But *you* have to do what works best for you."],
		["Claudia", "Then, reflect on your performance to see what to change and what to stick with."],
		["Calypso", "You're right. If I can't figure this out, how will I get anywhere?"],
		["Calypso", "Thank you, stranger."],
		["Calypso", "I feel a little bit better, and I'll continue to think about applying batching."],
		["Claudia", "I'm glad I was able to help."]
	],

	Corculum: [
		["Corculum", "What's up? You got any money?"],
		["Claudia", "I have mountains of money."],
		["Corculum", "Cough it up if you value your life."],
		["Claudia", "Hey now, you don't need to get violent just yet."],
		["Claudia", "First, you need to answer an important question."],
		["Corculum", "Huh? What are you talking about?"],
		["Claudia", "Think about the supposed number '0.999...'."],
		["Claudia", "The 9s repeat *infinitely*!"],
		["Corculum", "What does this have to do with money?"],
		["Claudia", "Well, this 0.999... number - would it be equal to 1.0?"],
		["Corculum", "Of course not. It's slightly smaller. What's your point?"],
		["Claudia", "HAHAH"],
		["Claudia", "Sorry, got carried away for a second."],
		["Claudia", "Well, here's the thing. It *is* actually equal to 1.0."],
		["Corculum", "Are you so rich that you can afford to skip math class? What's with this nonsense?"],
		["Claudia", "Think about it. I'll give you three example explanations."],
		["Corculum", "I don't need an explanation! It's obviously wrong!"],

		["Claudia", "First, consider how we can tell that two numbers are different."],
		["Claudia", "If we subtract one from the other, and the result is 0, then they're the same."],
		["Claudia", "5 and 5, for example, are the same number. So, their difference is 0. 5 - 5 = 0."],
		["Claudia", "5 and 6, for example, are different numbers. So, their difference isn't 0. 6 - 5 = 1."],
		["Corculum", "That's obvious! I'm past Grade 1, you know."],
		["Claudia", "Okay, then prove it. Here's the important part."],
		["Claudia", "What number do you get when you subtract 0.999... from 1?"],
		["Corculum", "Uh..."],
		["Claudia", "Spoiler alert: it's 0."],
		["Corculum", "N-gh! NO! It's not!"],
		["Claudia", "What is it, then?"],
		["Corculum", "It's, uh, 0.000... followed by a 1, at the end?"],
		["Claudia", "And how many 0s are there in that chain?"],
		["Corculum", "A ton! Millions!"],
		["Claudia", "Ha ha! No, that's not quite correct."],
		["Claudia", "'Millions' is nothing in the face of infinity, which is how many 9s there are in 0.999..."],
		["Claudia", "So, in your 'solution', there should be infinite 0s."],
		["Corculum", "Okay, well there you have it, then. If you already know, why ask me?"],
		["Claudia", "No, that's wrong! There *can't* be infinite 0s, because there's a 1 at the end."],
		["Corculum", "What's wrong with that?"],
		["Claudia", "What digit would the 1 be at? It can't possibly be there if there are infinite 0s first."],
		["Corculum", "Your argument is unconvincing. It's obvious to me that 1 - 0.999... = 0.000...1."],

		["Claudia", "If you can't comprehend that, then let's try something else."],
		["Claudia", "Let's try another experiment."],
		["Claudia", "Think of a variable x, and call it 0.999..."],
		["Claudia", "Now, we have x = 0.999..."],
		["Claudia", "Then, multiply both sides by 10."],
		["Claudia", "We'd have 10x = 9.999..."],
		["Claudia", "Next, subtract the original equation. Since the values are equal, this equation will continue to be equal."],
		["Claudia", "We'd get (10x - x) = (9.999... - 0.999...)"],
		["Claudia", "We're left with 9x = 9."],
		["Claudia", "Divide both sides by 9, and we get x = 1."],
		["Corculum", "Oh, Wai-"],
		["Claudia", "But, we initially defined x as 0.999... So, if it's both 1 and 0.999..., it means that the two are equal!"],
		["Corculum", "No, that doesn't make sense..."],
		["Corculum", "You must have made some kind of mistake in there."],
		["Corculum", "I'm not a math professor or anything..."],
		["Claudia", "(Clearly not.)"],
		["Corculum", "But you know even less if you think that 0.999... = 1. You must have done some kind of trick."],
		["Corculum", "Maybe you divided by 0 or something. You can't do that"],
		["Claudia", "Do you have amnesia as well? I divided by 9, not 0."],
		["Corculum", "Ugh! Stop trying to confuse me! It's not true!"],

		["Claudia", "Fine, here's one more."],
		["Corculum", "Enough already..."],
		["Claudia", "Don't worry, it's a simple one. You like simple, don't you? It must be familiar."],
		["Corculum", "Stop..."],
		["Claudia", "Consider the fraction 1/3."],
		["Claudia", "When you multiply by 3, you get 1/3 * 3 = 1, simply through the definition of a reciprocal."],
		["Claudia", "But, what's the decimal form of 1/3? It's 0.333..."],
		["Claudia", "And, what happens when you multiply 0.333... by 3? You get 0.999..., which hence has to equal 1."],
		["Corculum", "No, that can't be right. 0.333... * 3 must be 1.0, not 0.999."],
		["Claudia", "Are you even listening to yourself?"],
		["Corculum", "Or, or, maybe 0.333... isn't actually equal to 1/3. It's slightly too small..."],
		["Claudia", "That's false too. What else would it be equal to?"],
		["Claudia", "Something like 0.333... + ϵ? That doesn't make any sense if you understand how infinitesimals work."],
		["Corculum", "Just... stop... I don't care anymore. Just leave."],
		["Claudia", "Do you still want my money?"],
		["Corculum", "No! I never want to see your face again!"],
		["Claudia", "Have a good rest of your day."]
	],

	Althea: [
		["Althea", "Is there any real worth in learning a new language?"],
		["Claudia", "Before the real clarification question comes, we need to clear up some context."],
		["Claudia", "Well, what do you define as 'worth'?"],
		["Claudia", "If it's completely subjective, how can you expect me to answer for you?"],
		["Althea", "I'm talking about practical applications."],
		["Claudia", "That idea is still kind of blurry..."],
		["Claudia", "Can doing something for the sake of enjoyment and amusement really be deemed 'practical' or 'impractical'?"],
		["Claudia", "Still, I think I generally understand what you're talking about."],
		["Althea", "Hopefully. It seems you haven't heard the word 'practical' used in enough contexts to intuitively grasp the meaning."],

		["Claudia", "Regardless, there are other clarification questions."],
		["Claudia", "Does this hypothetical language-learner already fluent in English? What about their country's language?"],
		["Althea", "Are you implying that English is more or less 'worth' learning than an arbitrary other language?"],
		["Claudia", "Of course I am. English is easily the most practical language to learn in terms of business opportunities."],
		["Claudia", "This is such an obvious point... there's no way you disagree, right?"],
		["Althea", "No, I was just wondering."],
		["Althea", "Anyway, let's say that it's a person who speaks English and lives here in Lerwick, where English is the predominant language."],
		["Althea", "No other language around here would provide significant 'business opportunities', as you put it."],
		["Althea", "So, is it worth learning for them?"],
		["Claudia", "That's slightly different from your original question."],
		["Claudia", "I guess it'd be hypocritical to say otherwise, though, considering that I'm already learning Rust."],
		["Althea", "Rust is n-"],
		["Claudia", "You're mistaken. Anyway, the point is that I still do it 'for fun'."],
		["Claudia", "Do you consider that as 'worth'?"],

		["Althea", "Hey, I brought up the topic theoretically."],
		["Althea", "If you're crazy enough to actually partake in the activity, there's another side I'm more interseted in."],
		["Claudia", "You want me to elaborate on why I want to understand Rust?"],
		["Althea", "No, I wanted to know what you're doing to learn Rust, and whether or not it's effective."],
		["Claudia", "Well, I do what any language-learner does."],
		["Claudia", "I memorize grammar and vocabulary from my Rust textbook."],
		["Claudia", "Then, I practice making up sentences."],
		["Althea", "And how often do you read native Rust material?"],
		["Claudia", "Huh? Why would I do something like that? I'm not very good yet, so I would't understand most of it."],
		[null, "Althea puts on a concerned, disappointed look."],
		["Althea", "And how is that going for you?"],
		["Claudia", "It's going great. I now know 300 words and recently passed the RLPT N5."],

		["Althea", "Take a step back."],
		["Althea", "Do you realize that your efforts, currently, are largely futile?"],
		["Claudia", "What do you mean? I just cited my decent RLPT performance..."],
		["Althea", "No, you're seeing it all wrong."],
		["Althea", "Your final goal is to be fluent in Rust."],
		["Althea", "So, it makes sense to measure success in fluency in Rust, right?"],
		["Claudia", "That's what I did..."],
		["Althea", "No, no you didn't. First, what do we mean by 'fluency'?"],
		["Claudia", "There are different aspects, each of which I'm striving for..."],
		["Althea", "That's right. Fundamentally, the four broader categories are reading, writing, speaking, and listening."],
		["Althea", "The better you can do these, the more fluent you are, and the more successful your method has been."],
		["Althea", "Now, what did RLPT measure?"],
		["Claudia", "It measured reading, listening, and a bit of writing?"],
		["Althea", "No, that's not true. In reality, it measured none of them."],
		["Claudia", "...?"],
		["Althea", "Think back to the format of the test. The key point is that none of the material was *natural*."],
		["Claudia", "What do you mean by 'natural', and why is it significant?"],
		["Althea", "I mean that all the language used as part of the test is fake."],
		["Althea", "It's made for a learner taking the test, not for a native speaker of Rust."],
		["Claudia", "So? I still passed."],
		["Althea", "What you passed wasn't a test on real Rust, but a test on test Rust."],
		["Althea", "Are you getting this or do you need me to explain it again?"],

		["Claudia", "Oh, I think I see what you mean."],
		["Claudia", "But, you're implying that 'test Rust' is somehow completely different from 'real Rust'."],
		["Claudia", "I'm assuming that native Rust speakers still wrote the test, so how can that be?"],
		["Althea", "The distinction is greater than you would think. Real speech can't simply be crafted on paper."],
		["Claudia", "But can you prove that?"],
		["Althea", "Take a real, native book that is written in Rust. How much can you understand?"],
		["Claudia", "Where can I g-"],
		[null, "Althea hands Claudia a sturdy pocketbook with a crab on the cover."],
		[null, "Claudia riffles through the book, seeming puzzled."],
		["Claudia", "It doesn't look familiar at all."],
		["Claudia", "Oh, wait, there's a word I know."],
		["Claudia", "That one means that the following paragraph is unsafe."],
		[null, "Claudia hands Althea back the book."],
		["Althea", "fn factorial(i: u64) -> u64 {"],
		["Althea", "    (2..=i).product()"],
		["Althea", "}"],
		["Claudia", "Uhh, what was that?"],
		["Althea", "That was *real* Rust, which you've never even heard before!"],
		["Claudia", "Wait, you know the language?"],
		["Althea", "Of course! I grew up with it!"],
		["Althea", "That's why it pains me to see you hoping to learn but going nowhere."],
		["Claudia", "Uh, how about this?"],
		["Claudia", "use std::ops::Add"],
		["Claudia", "That's my favourite line."],
		["Althea", "See? Even in such a short sentence, you've already made a terrible mistake."],
		["Claudia", "Are you sure you know what you're talking aout?"],
		["Claudia", "How come other Rust speakers have complimented me in the past."],
		["Althea", "That's because they want to encourage you! You're not actually good at all!"],
		["Claudia", "W-what? No, they sweared that I was good."],
		["Althea", "That's just the polite nature of the Rust culture! Get over yourself, Claudia!"],

		["Claudia", "Okay, okay. I've heard enough of your complaining."],
		["Claudia", "What, then, do *you* think is the better way to learn?"],
		["Althea", "Well, think about your own experience."],
		["Althea", "You've failed to learn Rust with this 'skill building' method, but you *have* had success in the past."],
		["Claudia", "When? What are you talking about?"],
		["Althea", "What other language you have already learned? One where you *did* reach fluency?"],
		["Claudia", "Hmmm..."],
		["Claudia", "I genuinely don't know. How would you if I don't?"],
		["Althea", "Because I can hear it! You've learned English!"],
		["Claudia", "English? But that's..."],
		["Claudia", "I learned it when I was still a baby. I don't even know how, and nobody can learn like that again..."],
		["Althea", "As a baby, you learned through massive input!"],
		["Althea", "All day, you would be hearing the English of your surroundings and your brain would be finding patterns."],
		["Althea", "That way, you built an intuitive model of the language."],
		["Claudia", "But I've lost that language pattern ability. I'm not a baby anymore."],
		["Althea", "What makes you think you've lost it?"],
		["Claudia", "You said it yourself! I'm failing to learn Rust."],
		["Althea", "You missed the idea completely."],
		["Althea", "As a baby, you learned through input. But you're not learning Rust through input."],
		["Althea", "So, how do you know that you're incapable of learning through input?"],
		["Claudia", "Oh... then..."],
		["Althea", "Exactly: you have no answer, because you have no reason to think you're incapable."],
		["Claudia", "So, what, then? I just have to hear a bit of Rust?"],
		["Althea", "Not 'a bit'. You need thousands of hours of Rust."],
		["Claudia", "Thousands of hours? W-What?"],
		["Claudia", "Also, wait. I've been picking up English for many years..."],
		["Claudia", "You want me to spend that long on Rust?"],
		["Althea", "First off, I did not misspeak when I said that you would need thousands of hours."],
		["Althea", "That's simply the nature of fluency. If you don't like it, then don't waste your time."],
		["Althea", "Where do you think my question about worth at the start came from?"],
		["Althea", "Besides, you said yourself that you enjoy it. So, I don't see what the problem is."],

		["Althea", "Next, you don't need to spend as long learning it as native speakers do."],
		["Claudia", "But they learned through input, and you want me to learn through input..."],
		["Althea", "Learning through input alone works, but it's not very efficient."],
		["Althea", "So, you need to supplement it with conscious study, as you've been doing."],
		["Claudia", "Wait, what? But you just spent the last ten hours dunking on what I've been doing?"],
		["Althea", "The problem wasn't that you were doing conscious study."],
		["Althea", "The problem is that it was the *only* study you were doing."],
		["Althea", "Most of your time has to be dedicated to input."],

		["Claudia", "I still have many questions..."],
		["Claudia", "Can I hear about people who have learned through input successfully?"],
		["Claudia", "What kinds of conscious study are most efficient?"],
		["Claudia", "What kind of input is more efficient?"],
		["Claudia", "What do I actually start doing today if I want to learn Rust?"],
		["Claudia", "How can I review the method without talking to you again?"],
		["Althea", "Well, it seems like you're interested in learning more, so I will redirect you."],
		["Althea", "If you are actually interested in learning a language, check out the website https://refold.la."],
		["Claudia", "Refold? Is this some kind of sponsor?"],
		["Althea", "No. I'm not at all affiliated."],
		["Althea", "The reason I'm promoting Refold is because I believe it can help you."],
		["Althea", "If you tell somebody that drinking water for optimal hydration is a good idea..."],
		["Althea", "...Does it mean that you are suddenly sponsored by water?"],
		["Claudia", "Well, 'water' itself is not an actual brand or organization, but I get your point."],
		["Claudia", "Thank you for informing me."],
		["Claudia", "After I install Nero Linux, I'll check it out."],
		["Althea", "Of course. Thank you for your interest in Rust."]
	],

	Daria: [
		["Daria", "Good evening, traveler."],
		["Daria", "Are you here to expel my financial issues?"],
		["Claudia", "In the context of coming to Lerwick in general, no."],
		["Claudia", "But in this moment, I'm interested in what's going on."],
		["Daria", "I'm overjoyed to hear your tolerance of support!"],
		["Daria", "My earnings have found their way to a measly $0.50 per day."],
		["Claudia", "Judging from the inflation rates, I know the purchasing power of $0.50."],
		["Daria", "How convenient! You must be in the know, as it is, that I seem enviable!"],
		["Claudia", "In terms of income, sure...?"],
		["Claudia", "Where's the problem?"],
		["Daria", "The source of my discontent, I'm afraid, is the future."],
		["Daria", "This grueling job I endure... it's burning me alive."],
		["Claudia", "I'm going to go ahead and assume that's figurative."],
		["Daria", "Quite soon, I will be incapable of continuing my ascent up the mountain."],
		["Daria", "When that time comes knocking, I will fall."],
		["Daria", "And this fall... will last too long, but not long enough."],
		["Daria", "Additionally, the base of the mountain is solid rock."],
		["Daria", "My brittle bones will shatter quickly and the only thing left will be a puddle of missed opportunities."],
		["Daria", "In that moment, I will have no choice but to accept the death of everything I hold dear."],
		["Claudia", "Hmm..."],
		["Claudia", "Well, you have two options. The first is to significantly extend your ascent."],
		["Claudia", "Then, you would hopefully suffocate before you hit the rock."],
		["Daria", "How can you expect me to agree to that?"],
		["Claudia", "The other, more favourable option, is to start climbing down."],
		["Claudia", "Once you're sufficiently low in altitude, jump into the grass, not the rock."],
		["Daria", "But where would the cushion of grass appear from? I am no Dorus..."],

		["Claudia", "The grass comes from a special magic called 'investing'."],
		["Daria", "Investing? I beg you, enlighten me."],
		["Claudia", "Right now, where are your savings sitting?"],
		["Daria", "They reside in my Asiagenus bank account."],
		["Daria", "The interest rate is 0.0001%: much more pleasing than the Glaber bank's 0.000099%."],
		["Claudia", "Essentially, your money is not gaining value. But is it losing value?"],
		["Daria", "I'm afraid so. This year's inflation rate has revealed itself as a 7%!"],
		["Claudia", "Wait, actually? That's higher than I thought."],
		["Claudia", "Anyway, it should usually be around 2.5%. Your 0.0% bank interest cannot help."],
		["Daria", "But it remains much higher than Glaber's!"],
		["Claudia", "That doesn't matter. Stop comparing garbage to garbage."],
		["Daria", "You dare insult Asiagenus!?"],
		["Claudia", "Instead, you need a much higher return."],
		["Claudia", "This way, you can not only match inflation but surpass it, making profit."],
		["Claudia", "Then, you can keep earning without 'enduring' your 'grueling job'."],
		["Daria", "Of course, the fantasy appears pleasant. But, a higher return than 0.0001%? Don't tell jokes, now!"],
		["Claudia", "I mean it genuinely. You can invest in the stock market!"],
		[null, "Daria gasps forcefully."],
		["Daria", "T-the, the s-stock market? No!"],
		["Claudia", "Why do you seem so averse?"],
		["Daria", "Even poor Daria understands that the selection of individual stocks is a mere delusion!"],
		["Daria", "You cannot time any market, even that of Lerwick!"],
		["Claudia", "I agree with your impressions of investing. However, you've failed to acknowledge something."],
		["Claudia", "There exists a specific investment known as an 'index fund'."],
		["Daria", "Index fund? What kind of nonsense are you spouting?"],
		["Claudia", "None, for the words I speak reflect the truth of reality."],
		["Claudia", "An index fund is an algorithmic selection of stocks."],
		["Claudia", "Generally, the idea is to maximize diversification across the market."],
		["Claudia", "Then, if certain companies go up or down in the shot-term, it's fine."],
		["Claudia", "...so long as your market increases in the long-term."],
		["Daria", "Which index fund, then, could you be referring to?"],
		["Claudia", "It's true that there are many different implementations."],
		["Claudia", "My personal recommendation is the S&P 500 index."],
		["Claudia", "There are different trackers of it, like the VOO."],
		["Daria", "But how is the S&P 500 formed?"],
		["Claudia", "The top 500 companies in the United States are gathered for the index."],
		["Claudia", "The bigger the company, the higher the stake."],
		["Daria", "Which god decides whether a company is 'big', or is bigger than another?"],
		["Claudia", "I'm not sure what the exact process is. I'd assume it's based on market cap?"],
		["Claudia", "(That answers the second question. The first question is irrelevant.)"],
		["Daria", "This news is largely cherishable, but I am yet to be sold..."],
		["Daria", "Why the top 500 and not 400, 600, 100, or 99999?"],
		["Daria", "Why does it focus on the US market? What's so special there?"],
		["Daria", "If this will net me a great return, why has it not already been explained?"],
		["Daria", "If anybody can earn, what results in the communal following of this idea?"],
		["Daria", "Where does the money creep out from under? Is somebody falling so that I can climb?"],
		["Daria", "My dog told me that the economy was a zero-sum game, which is the case, is it not?"],
		["Claudia", "Uhh... well, historically..."],
		["Daria", "W-wait, could it be? You're flustered by such simple questions?"],
		["Claudia", "I mean, I've already told you the gener-"],
		["Daria", "If your cluelessness reaches such heights, why did you bother in the first place?"],
		["Daria", "How can you teach what you do not understand yourself?"],
		["Claudia", "Come on, surely this has be-"],
		["Daria", "I hereby declare your input 'ignorable'."],
		["Daria", "Next time you talk to somebody, consider the idea that their time should be respected."],
		["Daria", "Now, leave."],
		["Claudia", "..."],
	],

	Musawer: [
		["Musawer", "Hey, is it hard for you to memorize the cosine law?"],
		["Claudia", "Yes, actually. I keep confusing the variables."],
		["Musawer", "Well, do I have the mnemonic for you!"],
		["Musawer", "Consider this *amazing* story:"],
		["Musawer", "Crocodile squared..."],
		["Musawer", "Is equal to alligator squared plus bread squared..."],
		["Musawer", "minus two alligator breads..."],
		["Musawer", "at the cost of Cows."],
		["Claudia", "..."],
		["Claudia", "Whoa..."],
		["Claudia", "That resonates with me on a spiritual level."],
		["Claudia", "It's ingrained in every pocket of my mind, permanently."],
		["Claudia", "Thank you, Musawer."],
		["Claudia", "I just have on question..."],
		["Claudia", "By what process did you reach this divine relevation?"],
		["Musawer", "Oh, you know, I was just doing my daily routine of fighting alligators with my bare hands."],
		["Musawer", "When I first started, I was very afraid of the alligators."],
		["Musawer", "But now... the alligators are afraid of me."],
		["Musawer", "This climate, however, houses both alligators and crocodiles."],
		["Musawer", "So, I made bread from the alligators and fed it to the crocodiles."],
		["Claudia", "And how did they respond?"],
		["Musawer", "The crocodiles, they sang a song of joy as they drowned."],
		["Musawer", "When I listened closely, I heard the trigonometric functions in the form of audio signals."],
		["Musawer", "This endowed me with the godly mnemonic."],
		["Claudia", "Interesting..."],
		["Claudia", "I'll have to try this alligator bread sometime."],
		["Claudia", "Maybe Frontinus has some..."]
	],
}

export default dialogue
