
// Dialogue inside Nero's house
const dialogue = {
	Mercury: [
		["Mercury", "Halt!"],
		["Mercury", "Who dares disturb the slumber of the emperor!"],
		["Claudia", "I've made 0 dB of sound while you're here yelling across the room."],
		["Claudia", "Are you familiar with the concept of 'inside vs outside voice'?"],
		["Mercury", "Are you certain that that's how the decibel system works?"],
		["Mercury", "How many times have you spoken to Alexander Bell? I'm his best friend."],
		["Claudia", "He doesn't exist yet. Regardless, Bell Labs made the system."],
		["Claudia", "Being friends with Alexander doesn't automatically make you an expert."],

		["Mercury", "Enough deception! You still haven't stated the excuse for your disturbance!"],
		["Claudia", "I'm here to see Nero. This is his house, right?"],
		["Mercury", "What gives you the right to visit? Are you aware of the admission policy?"],
		["Claudia", "Well, I'm Nero's step-sister. Therefore, I can skip your policy."],
		["Mercury", "Wait, you're Octavia?"],
		["Claudia", "Y-yes?"],
		["Mercury", "O-ohh... Then, uh, move on ahead..."],
		["Mercury", "Btw, after you get banished, start 'preparing'."],
		["Claudia", "What? From where, and by whom?"],
		["Mercury", "Actually... never mind, sorry. Good luck."],
		["Claudia", "...?"]
	],

	Hector: [
		["Claudia", "Hey, what's the deal with this mounted armour that you're next to?"],
		["Claudia", "What's the point of it being here? Is it a display of wealth?"],
		["Hector", "Uhh, I don't work here. I was just having a nap."],
		["Claudia", "Oh, sorry for bothering you."],
		["Hector", "It's fine. I'm used to misfortune."],
		["Hector", "Anyway, you're right that there's no particular practical purpose."],
		["Hector", "Usually, it makes more sense for the armour to be stored elsewhere."],
		["Claudia", "In the armoury?"],
		["Hector", "Yes, or simply along with the rest of the knight's possessions, in concealed storage."],
		["Hector", "In the context of this house, I'd assume that its purpose is decorative."],
		["Claudia", "I see. How come Nero chose to mount it in this room specifically?"],
		["Claudia", "To me, it makes more sense to maximize the decoration in the very first room."],
		["Hector", "I think you've had enough answers from me."],
		["Hector", "Try really taking a stab at the question on your own, okay?"],
		["Hector", "My only hint would be that Nero might not have been the authority on its location."],
		["Claudia", "Hmm... okay..."]
	],

	Serapio: [
		// Wikipedia as a valid source
		["Serapio", "Hey! You may not pass this room unless you solve my riddle."],
		["Claudia", "Why?"],
		["Serapio", "W-why are you asking that? Just solve the riddle or go home, okay?"],
		["Claudia", "I mean, I can try solving it if you want, but you're not going to convince me that it's mandatory."],
		["Claudia", "Well, what's the riddle?"],
		["Serapio", "Prepare for your mind to be puzzled..."],
		["Serapio", "You will confuse yourself so intensely that tears will fall from your eyes!"],
		["Claudia", "Just say it already."],
		["Serapio", "Okay, okay. The riddle... is this:"],
		["Serapio", "What's a good website for learning about arbitrary topics?"],
		["Claudia", "..."],
		["Claudia", "How is that a riddle?"],
		["Serapio", "Oh? Are you so easily stumped that you need to jump to the 'it's not a riddle' strategy?"],
		["Claudia", "I mean, I can tell you my opinion on the topic, but that wouldn't 'solve' any riddle."],
		["Serapio", "...Can you solve it or not?"],
		["Claudia", "..."],
		["Claudia", "Wikipedia is a good website for learning."],
		["Claudia", "It compiles information from many other sources into the same article, making it efficient."],
		["Claudia", "Subtopics are hyperlinked as they come up, making it easy to discover prerequisites."],
		["Claudia", "Since it's run by the community, content is dictated by interest rather than financial incentives."],
		["Serapio", "W-Wikipedia!? No!"],
		["Claudia", "?"],
		["Serapio", "B-but, Wikipedia isn't a trusted source! My English teacher said it was bad!"],
		["Claudia", "Do you blindly take the word of supposed authority as fact?"],
		["Claudia", "What justification did this teacher have for slandering Wikipedia?"],
		["Serapio", "Well, a-anybody can edit, right? So there's no c-credibility!"],
		["Serapio", "I could write blatantly false information myself, and nobody w-would know, r-right?"],
		["Claudia", "First of all, calm down."],
		["Claudia", "Second, vandalizing Wikipedia isn't as simple as you describe."],
		["Claudia", "On Wikipedia, each piece of information is paired with its respective source."],
		["Claudia", "So, if you wanted to add your own information, you'd need a source to go with it."],
		["Claudia", "If the source is non-existent or uncredible, your edit would be reverted."],
		["Serapio", "Wait, really? Who is there to moderate that?"],
		["Claudia", "As I already said, it's run by the community."],
		["Claudia", "People like you and me can edit and 'watch' pages for further edits."],
		["Claudia", "Then, when I see a malicious edit, I can quickly revert it."],
		["Claudia", "For example, take a look at the edit history of the Enbridge article."],
		["Serapio", "No... there must be some mistake. There's no way... *Wikipedia*... actually works..."],
		["Claudia", "It's seeming more and more to me that you're overwhelmingly biased on the topic."],
		["Claudia", "Why not solve the riddle of your own academic dishonesty before attacking others?"],
		["Serapio", "..."],
	],

	Nero: [
		["Nero", "Wassup?"],
		["Claudia", "..."],
		["Claudia", "The ceiling is up."],
		["Nero", "Oh? You find it funny to bully children?"],
		["Claudia", "When d-"],
		["Nero", "Wrong! Lemme give you some truth:"],
		["Nero", "Your notion of direction is the literal definition of narrow-minded!"],
		["Nero", "How dare you declare that the ceiling is 'up'?"],
		["Nero", "You implying that our perspective is significant?"],
		["Nero", "From the perspective of Musawer's alligators, only the sky is up."],
		["Claudia", "Have you ever heard of implication before?"],
		["Claudia", "Your original question, 'What's up?', sta-"],
		["Nero", "OBJECTION"],
		["Nero", "My question was 'Wassup?'."],
		["Claudia", "Okay."],
		["Claudia", "Our perspective was implied by the fact that you were asking me with no stated context."],
		["Claudia", "If I enter the room and ask 'Do you have an apple?', do you see what's being implied?"],
		["Nero", "...That you want an apple?"],
		["Claudia", "Yes, but you missed the point."],
		["Claudia", "I'm implying that you, Nero, are responsible for answering."],
		["Claudia", "You wouldn't then say..."],
		["Claudia", "'Oh, how narrow-minded of me to assume that the question is intended for me.'"],
		["Nero", "H-huh?"],

		["Claudia", "Whatever, I don't care about that anymore."],
		["Claudia", "Where's your ROM?"],
		["Nero", "Oh ho! Come for the famous Nero Linux ROM?"],
		["Claudia", "Please tell me that's rhetorical..."],
		["Nero", "Well, don't get your hopes up."],
		["Nero", "What you may not be aware of is that the Nero Linux ROM does not exist as you believe it does."],
		["Claudia", "Uh, yes it does. My mom said th-"],
		["Nero", "Wrong! Only I, Nero, exist. To construct the CD-ROM, you would need to burn me alive."],
		["Claudia", "So your melted organs would turn into data? Why?"],
		["Nero", "Those are the rules, fool. Therefore, your journey ends here. Be on your way."],
		["Claudia", "Are you under the impression that I'm under a moral dilemma right now?"],
		["Nero", "Well, yeah."],
		["Nero", "Killing me would be morally wrong but favourable for your computer."],
		["Nero", "Leaving me would be morally right but unfavourable for your computer."],
		["Nero", "Am I right?"],
		["Claudia", "Nope. You're the narrow-minded one to assume my moral system."],
		["Claudia", "Your life holds no inherent value to me."],
		["Nero", "Huh? Am I talking to Tiberius?"],
		["Claudia", "Wait, he's a moral relativist?"],

		["Claudia", "Oh, that reminds me... how does this room exist?"],
		["Claudia", "Shouldn't it be geometrically impossible?"],
		["Nero", "Hah. I have no sympathy for fools like you...."],
		["Nero", "Allowing yourself to be governed by the laws of geometry? PATHETIC"],
		["Nero", "I've transcended such formalities. I can teleport."],
		["Nero", "So, the more important discussion is *whether* you can kill me."],
		["Claudia", "That won't be a problem."],
		["Claudia", "Nero Claudius Caesar Augustus Germanicus! Prepare for the end of your short life."],
		["Nero", "Ha ha ha... fool..."],

		["Nero", "I'm so overflowingly confident in myself that I'll give you a tip."],
		["Nero", "Around the room, you will encounter purple (#2B193D) squares."],
		["Nero", "If you pick one up, your next attack will do more damage."],
		["Nero", "This encourages you to move around the room while fighting instead of staying in the same spot."],
		["Nero", "It's peak game design, okay?."],
		["Claudia", "Thanks for making it even easier to kill you, idiot."]
	]
}

export default dialogue
