// Dialogue inside Tiberius' house, excluding Augustus

const dialogue = {
	Claudius: [
		["Claudia", "Dad? How'd you get here?"],
		["Claudius", "...Listen."],
		["Claudia", "..."],
		["Claudius", "You're interested in finding a 𝗽𝗮𝘀𝘀𝘄𝗼𝗿𝗱, are you not?"],
		["Claudia", "Sure?"],
		["Claudius", "I'll help you out."],
		["Claudius", "The password is #@abc$&"],
		["Claudia", "The literal string?"],
		["Claudius", "No, of course not."],
		["Claudius", "It's not supposed to be difficult to figure out, okay?"],
		["Claudia", "Then, what is 'b'?"],
		["Claudius", "Hmm, let's pick a number."],
		["Claudia", "9.9?"],
		["Claudius", "Sure, 'b' can be 9.9."],
		["Claudius", "The rest is simple."],
		["Claudia", "Hmm... I wonder if this is necessary..."]
	],

	TiberiusBase: [
		["Tiberius", "ayyyyyyy :D"],
		["Claudia", "Oh, it's you."],
		["Tiberius", "hows it goin bro!"],
		["Claudia", "I'm just loo-"],
		["Tiberius", "dw, ik what ur thinking"],
		["Tiberius", "u want MY time machine, ya!"],
		[null, "Claudia recalls her sorry exchange with Frontinus."],
		["Claudia", "Well, it's true that it could be helpful to me."],
		["Claudia", "Are you even using it for anything productive?"],
		["Tiberius", "lol u sound like pretty desprate bro"],
		["Claudia", "...That doesn't answer my question."],
		["Tiberius", "well i cant just give it out to randos lmfao"],
		["Claudia", "My point is that it doesn't look like you're doing anything particularly useful."],
		["Tiberius", "bruhhhhh u really want it"],
		["Tiberius", "idk i dont c a complusion to give u it"],
		["Claudia", "..."],
		["Tiberius", "o, how about this"],
		["Tiberius", "if u can beat me in an argument, il give u it"],
		["Claudia", "Argument? What are you talking about?"],
		["Tiberius", "well, i only hold positions on 2 topics"],
		["Tiberius", "k?"],
		["Claudia", "That doesn't make any sense, but which two topics are you referring to?"],
		["Tiberius", "idrk names or anything but i can explain"],

		["Tiberius", "so basically"],
		["Tiberius", "the first idea is that i dont rly think that anything is right or worng"],
		["Claudia", "Right or wrong? You mean, in the the context of morality?"],
		["Tiberius", "morilaty? uh idk :|"],
		["Claudia", "Well, here's an example."],
		["Claudia", "You don't think that unjustified murder is wrong? Because nothing is wrong?"],
		["Tiberius", "ye"],
		["Claudia", "...What? Why?"],
		["Tiberius", "wdym why"],
		["Tiberius", "its up to u to explain why its wrong"],
		["Claudia", "Well, if person A unjustifiably murders person B..."],
		["Claudia", "B experiences pain and discomfort. Why should they have to go through that?"],
		["Tiberius", "im not sayin they should have to"],
		["Tiberius", "just that its not wrong for B to experience that"],
		["Claudia", "So, you hold no value of suffering at all?"],
		["Tiberius", "why should i"],
		["Claudia", "Then, you have no argument against somebody wishing to harm you?"],
		["Tiberius", "ofc i do"],
		["Tiberius", "if they harm me, the police will get em"],
		["Tiberius", "so its bad for them"],
		["Claudia", "That's a pragmatic reason, not a moral reason, right?"],
		["Tiberius", "idk"],
		["Claudia", "So, if there were no practical negative consequences, you'd be fine with them doing it?"],
		["Tiberius", "i wouldnt be fine with it but it wouldnt be wrong"],
		["Claudia", "Doesn't it make more sense to value others?"],
		["Claudia", "If you can socially agree that suffering is wrong, it opens opportunities to help each other."],
		["Claudia", "You don't hurt others if you don't have to, and they agree not to hurt you if they don't have to."],
		["Tiberius", "still doesnt mean that its wrong for them to hurt you"],
		["Tiberius", "it would just be a bad idea"],
		[null, "Claudia sighs."],
		["Claudia", "Okay, picture this hypothetical."],
		["Claudia", "If you push a button, your family dies but you get a free computer."],
		["Tiberius", "is it a good computer"],
		["Claudia", "Sure."],
		["Tiberius", "uh"],
		["Claudia", "Well, if you don't value suffering, the obvious answer is to push the button."],
		["Claudia", "Why care if your family dies?"],
		["Tiberius", "idk i dont think i would push it"],
		["Claudia", "Oh? Why is that?"],
		["Claudia", "Don't tell me that you're going to start selectively following common morality..."],
		["Tiberius", "uhhh"],
		["Tiberius", "o how bout this explanatino"],
		["Tiberius", "my family dying would make me sad"],
		["Tiberius", "i dont want to feel sad"],
		["Tiberius", "so i wont press the button"],
		["Tiberius", "the free computer wont make me unsad"],
		["Claudia", "Really? How about this one?"],
		["Claudia", "You can press a button and get $0.01."],
		["Claudia", "But, a random person is now put in front of you and tortured for a while, until their death."],
		["Claudia", "Would you press it? $0.01 is better than nothing, but is it worth it?"],
		["Tiberius", "uh"],
		["Tiberius", "same answer ig"],
		["Claudia", "And the same justification?"],
		["Tiberius", "probably"],
		["Claudia", "Judging from your response, it seems like you do believe that suffering is wrong."],
		["Claudia", "However, because you don't like that idea (for some reason), you hide behind psychological egoism."],
		["Claudia", "When you propose that seeing the person makes you 'sad', it means that you see it as wrong."],
		["Tiberius", "nope"],
		["Claudia", "With this logic, you would probably feel 'sad' for person B from earlier."],
		["Claudia", "If you saw it in real life, that is. You're just in denial about your ideas."],

		["Tiberius", "u rly arnt giving any good points lol"],
		["Tiberius", "ppl like u come here everyday w ith this stuff"],
		["Claudia", "You mean 'every day'? How are you this illiterate?"],
		["Claudia", "It's honestly difficult to understand you."],
		["Tiberius", "lmfaooooo"],
		["Tiberius", "ur so bad at arguing that u have to start attackign me"],
		["Tiberius", "cuz u cant touch my arguments"],
		["Tiberius", "lmao how can you be this dumb"],
		[null, "Claudia sighs."],
		["Claudia", "You know, let's just move on to the next topic."],
		["Claudia", "But first, I think that there's a bit too much tension. Don't you think so?"],
		["Tiberius", "idk u tell me"],
		["Claudia", "Tell me about yourself. What kinds of foods do you like to eat?"],
		["Tiberius", "uh, i like candy"],
		["Tiberius", "especially aspertane"],
		["Claudia", "Do you mean 'Aspartame'?"],
		["Tiberius", "idk probably"],
		["Claudia", "Nobody would call that 'candy'."],
		["Tiberius", "dc bro"],
		["Claudia", "I'm guessing you like processed meat as well..."],
		["Tiberius", "o but there is stuff that i rly wouldnt eat"],
		["Tiberius", "spficialy, i cant have peanuts"],
		["Claudia", "Are you allergic?"],
		["Tiberius", "ye"],
		["Tiberius", "its really bad"],
		["Claudia", "Tiberius has a 𝘀𝗲𝘃𝗲𝗿𝗲 𝗮𝗹𝗹𝗲𝗿𝗴𝘆 𝘁𝗼 𝗽𝗲𝗮𝗻𝘂𝘁𝘀. I should remember that."],
		["Tiberius", "who u talking to lol"],
		["Tiberius", "and why"],
		["Claudia", "Anyway, I think that's enough conversation."],
		["Claudia", "What's the other position you had?"],

		["Tiberius", "its about reality"],
		["Tiberius", "i dont know that anything is true, bro"],
		["Claudia", "So, you don't know that I'm standing here, in front of you?"],
		["Tiberius", "nope, theres now way to know"],
		["Claudia", "Well, you can see me, using your eyes."],
		["Tiberius", "but how do i know that my eyes are accurate"],
		["Claudia", "Have they been inaccurate in the past?"],
		["Claudia", "When you walk up a staircase, you see the steps (and your feet) with your eyes."],
		["Claudia", "You position your limbs accordingly, and you feel the steps with your feet."],
		["Claudia", "The result is that you go up the stairs successfully, without falling down."],
		["Tiberius", "well, how would i know that i didnt fall down"],
		["Tiberius", "again, bc of my eyes, which is just a circle of logic"],
		["Tiberius", "same with my sense of touch"],
		["Tiberius", "maybe my skin is inaccurate, telling me that im touching the steps"],
		["Tiberius", "also, ye, my eyes have been inaccurate in the past"],
		["Tiberius", "like, when im tired, i see spiders on the walls sometimes out of the corner of my eye"],
		["Claudia", "Uh..."],
		["Tiberius", "but when i look closely, they're not there"],
		["Tiberius", "thats not really what im talking abou tho"],
		["Claudia", "How would that make sense? You're worried that your optic nerve is dysfunctional?"],
		["Tiberius", "no"],
		["Tiberius", "it doesnt matter if it makes sense"],
		["Claudia", "What? Why?"],
		["Tiberius", "just because we dont think something makes sense, it doesnt mean it cant exist"],
		["Claudia", "So, if a = b, you don't *know* that b = a?"],
		["Tiberius", "it makes sense under my logical system"],
		["Tiberius", "but i cant prove that my logical system is true"],
		["Claudia", "How would it not be?"],
		["Tiberius", "again, just bc u feel like it has to be true, it doesnt mean it does"],
		["Tiberius", "just cuz u cant imagine something doesnt mean it cant exist lol"],
		["Claudia", "Well, you can't make any claim, then."],
		["Claudia", "You can't say that you don't know anything if you don't know that you don't know anything."],
		["Tiberius", "k so idk if ik that idk"],
		["Tiberius", "and idk if ik that idk if ik that idk"],
		["Tiberius", "etc"],
		["Claudia", "You're accepting that some sort of logic exists to make these arguments in the first place..."],
		["Tiberius", "no"],

		["Claudia", "I've had enough of this. But I still don't have the time machine..."],
		["Claudia", "Maybe there's a different way of getting it from him..."]
	],

	TiberiusTransact: [
		["Claudia", "Hey, Tiberius."],
		["Tiberius", "wh-"],
		["Claudia", "You have a time machine, don't you?"],
		["Claudia", "But you're only willing to give it up if somebody beats you in an argument?"],
		["Tiberius", "lol whu told u that"],
		["Claudia", "Does it matter?"],
		["Tiberius", "idk guess not"],
		["Claudia", "Well, there's a change of plans."],
		["Tiberius", "wdym"],
		["Claudia", "Take a look at this..."],
		[null, "Claudia takes a pack of peanuts out of her pocket."],
		["Tiberius", "wwwhatt! no!"],
		["Tiberius", "im allergic to peanuts! get rid of those! wtf"],
		["Claudia", "I'm aware. Why do you think I brought this?"],
		["Claudia", "Considering the severity of your allergy, this should be enough to kill you."],
		["Tiberius", "wtf ru doing!!?"],
		["Claudia", "Oh, but there is one thing that could make me reconsider."],
		["Tiberius", "u want my time machine? fine! just throw those away!"],
		[null, "Tiberius frantically hands Claudia the time machine."],
		[null, "Claudia puts the peanuts back in her pocket."],
		["Claudia", "That wasn't so hard, now, was it?"],
		["Tiberius", "..."],
		["Tiberius", "tf is wrong with u"]
	],

	TiberiusAftermath: [
		["Tiberius", "...tf is wrong with u"],
		["Tiberius", "ur so bad at arguing that you had to resort to threatening me..."],
		["Tiberius", "howd u even know that im allergic? u a stalker r somting?"],
		["Claudia", "Say whatever you want. I'm still the winner."]
	]
}

export default dialogue
