#!/bin/sh

# Generate .txt files for each problem.

cd problems
rm *txt

curl -O https://norvig.com/easy50.txt

num=1
while read -r line
do
	echo "$line" | grep "=" &&
		num=$((num+1)) &&
		continue

	echo "$line" >> "$num.txt"

done < easy50.txt

rm easy50.txt
